# Original by Purpur (https://github.com/PurpurMC/Purpur)

name: Performance Problem
description: Report performance related problems or other areas of concern
body:
  - type: markdown
    attributes:
      value: |
        Before reporting performance problems here, please make sure you are on the latest version of Bee.
  - type: input
    attributes:
      label: Spark link
      description: We ask that all Spark profilings are shared through a link, not a screenshot. Screenshots inhibit our ability to figure out the real cause of the issue.
      placeholder: Output of /spark profiler --timeout 300
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of issue
      description: Please describe your issue in detail.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bee version
      description: |
        Run `/version` on your server and **paste** the full, unmodified output here.
        "latest" is *not* a version; we require the output of `/version` so we can adequately track down the issue.
        Additionally, do NOT provide a screenshot, you MUST paste the entire output.
        <details>
        <summary>Example</summary>

        ```
        > version
        [21:42:44 INFO]: Checking version, please wait...
        [21:42:44 INFO]: Current: git-Bee-"c153019" (MC: 1.19.3)*
        You are running the latest version
        Previous version: git-Bee-"7f673ca" (MC: 1.19.3)
        ```

        </details>
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I am running the latest version of Bee available from https://github.com/simplest-softwares/Bee/releases.
          required: true
        - label: I have searched for and ensured there isn't already an open issue regarding this.
          required: true
        - label: My version of Minecraft is supported by Bee.
          required: true
  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below, if any.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false
